export const baseAPIUrl ='https://glacial-brook-14205.herokuapp.com/'
export const docAPIUrl='https://powerful-fortress-74746.herokuapp.com/'
export const dentistAPIUrl='https://obscure-river-29490.herokuapp.com/'
export const nurseAPIUrl='https://boiling-wave-75882.herokuapp.com/'
export const obsteAPIUrl='https://intense-hollows-61104.herokuapp.com/'